services:
  webserver:
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - db_net
    depends_on:
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile


  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "yarn install && npx prisma db push && yarn start:dev"
    user: "1000:1002"
    volumes:
      - ./backend:/app
    ports:
      - "8100:8100"
    env_file:
      - ./backend/.env
    networks:
      - db_net
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - db_net

  frontend:
    restart: always
    container_name: frontend
    command: sh -c "yarn install && yarn dev"
    user: "1000:1002"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db_net

volumes:
  db-data:

networks:
  db_net:
    driver: bridge
