name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: docker stop
        run: docker compose down -v
      - name: Get code
        uses: actions/checkout@v4
      - name: docker start
        run: docker compose up -d