name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMO
        uses: docker/setup-qemu-action@v2
      - name: publish
        uses: 0x4r45h/docker-compose-ci@v0.1.0