name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMO
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest